### ISSUE TITLE
got an unexpected keyword argument 'flush'

### ISSUE THREAD

**Issue by attibalazs** [fastai/fastprogress#47] opened 2020-01-20 14:03 UTC
```
  File "C:\Anaconda\envs\fv\lib\site-packages\fastprogress\fastprogress.py", line 247, in on_update
    if printing(): WRITER_FN(to_write, end=end, flush=FLUSH)
TypeError: log_fastai_msg() got an unexpected keyword argument 'flush'
```
hi,
any ideas why i am getting this error ?

if i try it out in the console it works, but when i run my fastai code i get the error.

```
WRITER_FN = print
WRITER_FN("hello", flush=True)

```
the above two lines work for me in a python console.

thanks!

**Comment by sgugger** [comment] 2020-01-27 19:00
What fastai code are you running exactly?

**Comment by sgugger** [comment] 2020-03-28 13:33
Closing since this has not been addressed in a long time. Please reopen with a clear reproducer.

**Closed by sgugger** 2020-03-28 13:33 UTC
