### ISSUE TITLE
AttributeError: 'NBMasterBar' object has no attribute 'out'

### ISSUE THREAD

**Issue by AlkaSaliss** [fastai/fastprogress#54] opened 2020-03-07 01:44 UTC
When using `learner.fit_flat_cos(n_epochs, cbs=[SaveModelCallback(path)])` it throws the exception
However when used without the callback, it works with no error

fast_progress version = `fastprogress-0.2.2`

Any idea of what is causing this bug ?

**Comment by nazmiasri95** [comment] 2020-03-16 09:58
I also had same issue

**Comment by sgugger** [comment] 2020-03-28 13:31
This is usually a residual error that comes after a real error in training, unrelated to fastprogress. This is why we always ask for the full stack trace when you file an issue, because it contains more information than the last error message.

Closing this issue, please reopen with a clear reproducer if needed.

**Closed by sgugger** 2020-03-28 13:31 UTC
